# Generated by Django 3.1.1 on 2020-09-26 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passwordresetcodes',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('code', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, upload_to='uploads/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('is_premium', models.BooleanField(default=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('location', models.TextField(blank=True, max_length=100)),
                ('website', models.TextField(blank=True, max_length=45)),
                ('twitter', models.TextField(blank=True, max_length=16)),
                ('facebook', models.TextField(blank=True, max_length=16)),
                ('instagram', models.TextField(blank=True, max_length=16)),
                ('github', models.TextField(blank=True, max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
