# Generated by Django 3.1.1 on 2020-09-28 08:47

from django.db import migrations, models
import django.db.models.deletion
import shots.models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShotsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=shots.models.ShotFilesPath)),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shots.shot')),
            ],
        ),
    ]
