# Generated by Django 3.1.1 on 2020-09-28 10:29

from django.db import migrations, models
import shots.models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0002_shotsfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='thumbnail',
            field=models.ImageField(default='some photo', upload_to=shots.models.ShotFilesPath),
        ),
        migrations.AlterField(
            model_name='shot',
            name='title',
            field=models.TextField(blank=True, max_length=48),
        ),
    ]
