# Generated by Django 3.1.1 on 2020-09-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0004_auto_20200928_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shot',
            name='published',
            field=models.DateTimeField(),
        ),
    ]
